USE ROLE IT_DEVELOPER;

-- Fetch the repository
ALTER GIT REPOSITORY STREAMLIT_DATA_EDITOR_GENERATOR FETCH;

-- Create Streamlit App
EXECUTE IMMEDIATE FROM '@"STREAMLIT_DATA_EDITOR_GENERATOR"."STREAMLIT_DATA_EDITOR_GENERATOR"/src/sql/SP_CREATE_STREAMLIT_APP.sql';

-- Create Config Table
EXECUTE IMMEDIATE FROM '@"STREAMLIT_DATA_EDITOR_GENERATOR"."STREAMLIT_DATA_EDITOR_GENERATOR"/src/sql/utils/SP_CREATE_CONFIG_TABLE.sql';

-- Create History Table
EXECUTE IMMEDIATE FROM '@"STREAMLIT_DATA_EDITOR_GENERATOR"."STREAMLIT_DATA_EDITOR_GENERATOR"/src/sql/utils/SP_CREATE_HISTORY_TABLE.sql';

-- Create Streamlit App Only (if needed)
EXECUTE IMMEDIATE FROM '@"STREAMLIT_DATA_EDITOR_GENERATOR"."STREAMLIT_DATA_EDITOR_GENERATOR"/src/sql/utils/SP_CREATE_STREAMLIT_APP_ONLY.sql';

